# -*- coding: utf-8 -*-
"""CIE1 29/7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oa6x9aNZDcpHWL9PxxwHtNG-kTylS06
"""

import pandas as pd
data = pd.read_csv("/content/mtcars.csv")
print(data)

import matplotlib.pyplot as plt
plt.scatter(data["wt"],data["mpg"])
plt.xlabel("weight")
plt.ylabel("mpg")
plt.title("relation between weight of the car and mpg")
plt.show()

import matplotlib.pyplot as plt
plt.hist(data['mpg'],bins=10,color='r',edgecolor='k')
plt.xlabel("mpg")
plt.ylabel("frequency")
plt.title("histogram of mpg")
plt.show()

